### ISSUE TITLE
Record type error

### ISSUE THREAD

**Issue by libertybell95** [7Cav/api#4]
Inconsistency between record types shown on 7cav website and API.

## Example:
**Record:** `Completed 62nd Combat Mission (Campaign Monday Madness September21. Operation Monday Madness 06SEP21)`

https://7cav.us/rosters/profile/457/ shows record Type as _Operation_
<img width="1136" alt="Screen Shot 2021-09-12 at 22 44 09" src="https://user-images.githubusercontent.com/39743780/133020856-46bb376f-a276-4ea6-9c8b-8107e0950e6c.png">

https://api.7cav.us/api/v1/milpacs/profile/id/457 shows recordType as _RECORD_TYPE_TRANSFER_
```json
{
      "recordDetails": "Completed 62nd Combat Mission (Campaign Monday Madness September21. Operation Monday Madness 06SEP21)",
      "recordType": "RECORD_TYPE_TRANSFER",
      "recordDate": "2021-09-07"
}
```

**Comment by SyniRon** [comment]
Closing as this issue seems resolved to have been resolved previously, current api returns the below

```json
           "recordDetails":"Completed 62nd Combat Mission (Campaign Monday Madness September21. Operation Monday Madness 06SEP21)",
           "recordType":"RECORD_TYPE_OPERATION",
           "recordDate":"2021-09-07"
       },
```
