### ISSUE TITLE
Username API is non functional.

### ISSUE THREAD

**Issue by Dippys** [7Cav/api#5]
![image](https://user-images.githubusercontent.com/52082595/147995284-1a8d9b82-6e11-4ffb-9dc6-7824ad4cd6e9.png)

**Comment by SyniRon** [comment]
Dug into this and it was never fully implemented, basically a placeholder that returns invalid data.

Will work on fixing this soon.

**Comment by Dippys** [comment]
> Dug into this and it was never fully implemented, basically a placeholder that returns invalid data.
> 
> Will work on fixing this soon.

Holy necro. Thanks for taking a look at this.
